[package]
name = "jolt_rust_cpp"
version = "0.1.0"
edition = "2024"

[dependencies]
cxx = "1.0.183"
# TODO(lucasw) keep glam in sync with jolt_rerun rerun version of glam
glam = "0.30.7"
noise = "0.9.0"

[build-dependencies]
cmake = "0.1.54"
cxx-build = "1.0"
