[package]
name = "jolt_rust_cpp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
cxx = "1.0.183"
noise = "0.9.0"
# TODO(lucasw) update to 0.25
rerun = "0.24.1"

[build-dependencies]
cmake = "0.1.54"
cxx-build = "1.0"
