name: Build jolt_rust_cpp

on:
  push:
  pull_request:

jobs:
  test-suite:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        rust_version: [stable]

    runs-on: ${{ matrix.os }}
    name: Tests - ${{ matrix.os }} ${{ matrix.rust_version }}

    steps:

      # checkout deletes the current directory, so checkout before curl into same dir
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: get vulkan sdk
      run: |
        pwd
        # TODO(lucasw) get windows sdk if in windows
        curl -o vulkan.tar.xz https://sdk.lunarg.com/sdk/download/1.4.321.1/linux/vulkansdk-linux-x86_64-1.4.321.1.tar.xz
        tar xf vulkan*.tar.xz
        source 1.4.321.1/setup-env.sh

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust_version }}

    # - uses: swatinem/rust-cache@v2

    - name: Install rerun
      run: |
        sudo apt-get install -yqq libasound2-dev libudev-dev libx11-dev
        sudo apt-get install -yqq libwayland-dev
        pip3 install rerun-sdk==0.24.1
        # cargo binstall rerun-cli
        # cargo binstall --force rerun-cli@0.24.1

    - name: Build debug
      run: |
        pwd
        source 1.4.321.1/setup-env.sh
        cargo build -vv

    - name: Build release
      run: |
        pwd
        source 1.4.321.1/setup-env.sh
        cargo build --release -vv
